import { useState } from "react";
import { Link } from "react-router";
import {
  Shield,
  TrendingUp,
  DollarSign,
  ArrowRight,
  Lock,
  CheckCircle2,
  Settings,
  Mail,
} from "lucide-react";
import { Button } from "../components/ui/button";
import { Slider } from "../components/ui/slider";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { motion } from "motion/react";
import { FadeUp } from "@/app/components/animations";
import { useReducedMotion } from "@/app/hooks/useReducedMotion";
import { FloatingBadgeGroup } from "@/app/components/FloatingBadge";

const formatCurrency = (value: number) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);

export function ROICalculator() {
  const prefersReducedMotion = useReducedMotion();
  const heroAnimation = prefersReducedMotion
    ? {}
    : {
        initial: { opacity: 0, y: 30 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 0.5, ease: [0.25, 0.1, 0.25, 1] },
      };

  const [patientCount, setPatientCount] = useState(500);
  const [duration, setDuration] = useState(6);
  const [reimbursementRate, setReimbursementRate] = useState(135);
  const [platformFee, setPlatformFee] = useState(50);

  // TODO: When backend is available, replace mailto with API call to send formatted HTML email via SendGrid/Resend
  const generateReportEmail = () => {
    const subject = encodeURIComponent("iRxReminder ROI Report");
    const body = encodeURIComponent(
`iRxReminder ROI Calculator Report
===================================

Configuration:
- Patients: ${patientCount.toLocaleString()}
- Duration: ${duration} months
- RPM Reimbursement Rate: ${formatCurrency(reimbursementRate)}/patient/month
- iRxReminder Platform Fee: ${formatCurrency(platformFee)}/patient/month

Projected Results:
- Reimbursable Revenue: ${formatCurrency(totalRevenue)}
- Program Cost: ${formatCurrency(totalCost)}
- Net Profit: ${formatCurrency(netProfit)}
- ROI Multiplier: ${roiMultiplier}x
- Payback Period: ${paybackMonths > 0 ? `~${paybackMonths} month(s)` : "Immediate"}

---
Generated by iRxReminder ROI Calculator
https://irxreminder.com/roi-calculator

Ready to see these results in your organization?
Schedule a pilot: https://irxreminder.com/schedule-pilot
`
    );
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  };

  const totalRevenue = patientCount * duration * reimbursementRate;
  const totalCost = patientCount * duration * platformFee;
  const netProfit = totalRevenue - totalCost;
  const roiMultiplier =
    totalCost > 0 ? (totalRevenue / totalCost).toFixed(1) : "0";
  const paybackMonths =
    reimbursementRate > platformFee
      ? Math.ceil(platformFee / (reimbursementRate - platformFee))
      : 0;

  return (
    <div className="bg-white">
      {/* Hero — Light */}
      <section className="bg-[#EEF4FF]">
        <div className="max-w-4xl mx-auto px-5 sm:px-8 py-24 text-center">
          <motion.div {...heroAnimation}>
            <p className="text-xs font-semibold uppercase tracking-[0.05em] text-[#1E56A0] mb-4">
              ROI Calculator
            </p>
            <h1
              className="text-4xl md:text-5xl font-bold text-[#171717] mb-3 tracking-[-0.02em]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Your Path to Reimbursable Remote Care
            </h1>
            <p
              className="text-xl sm:text-2xl font-bold text-[#1E56A0] tracking-[-0.01em] mb-6"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Calculate Your ROI
            </p>
            <p className="text-xl text-[#737373] max-w-2xl mx-auto">
              See how much reimbursable revenue your health system could
              generate with iRxReminder
            </p>
          </motion.div>
        </div>
      </section>

      {/* Calculator — Split Layout */}
      <section className="py-16 -mt-12">
        <div className="max-w-6xl mx-auto px-5 sm:px-8">
          <FadeUp>
            <div className="bg-white rounded-2xl p-8 md:p-12 border border-[#E5E5E5]/60 shadow-lg shadow-[#171717]/5">
              <div className="grid lg:grid-cols-2 gap-12 lg:gap-16">
                {/* Left: Input Controls */}
                <div>
                  <h2
                    className="text-2xl font-bold text-[#171717] mb-8 tracking-[-0.01em]"
                    style={{ fontFamily: "var(--font-display)" }}
                  >
                    Adjust Your Parameters
                  </h2>

                  <div className="space-y-8">
                    {/* Patient Count */}
                    <div>
                      <div className="flex justify-between items-center mb-3">
                        <Label
                          htmlFor="patient-count"
                          className="text-base font-semibold"
                        >
                          Number of Patients
                        </Label>
                        <span
                          className="text-2xl font-bold text-[#0F2B57] tracking-tight"
                          style={{ fontFamily: "var(--font-display)" }}
                        >
                          {patientCount.toLocaleString()}
                        </span>
                      </div>
                      <Slider
                        id="patient-count"
                        min={10}
                        max={1000}
                        step={10}
                        value={[patientCount]}
                        onValueChange={(value) => setPatientCount(value[0])}
                        className="mb-2"
                      />
                      <div className="flex justify-between text-xs text-[#737373]">
                        <span>10</span>
                        <span>1,000</span>
                      </div>
                    </div>

                    {/* Duration */}
                    <div>
                      <div className="flex justify-between items-center mb-3">
                        <Label
                          htmlFor="duration"
                          className="text-base font-semibold"
                        >
                          Monitoring Duration
                        </Label>
                        <span
                          className="text-2xl font-bold text-[#1E56A0] tracking-tight"
                          style={{ fontFamily: "var(--font-display)" }}
                        >
                          {duration} {duration === 1 ? "month" : "months"}
                        </span>
                      </div>
                      <Slider
                        id="duration"
                        min={1}
                        max={12}
                        step={1}
                        value={[duration]}
                        onValueChange={(value) => setDuration(value[0])}
                        className="mb-2"
                      />
                      <div className="flex justify-between text-xs text-[#737373]">
                        <span>1 month</span>
                        <span>12 months</span>
                      </div>
                    </div>

                    {/* Reimbursement Rate */}
                    <div>
                      <Label
                        htmlFor="reimbursement"
                        className="text-base font-semibold mb-3 block"
                      >
                        Reimbursement Rate per Patient/Month
                      </Label>
                      <div className="flex items-center gap-4">
                        <div className="relative flex-1 max-w-xs">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[#737373]">
                            $
                          </span>
                          <Input
                            id="reimbursement"
                            type="number"
                            value={reimbursementRate}
                            onChange={(e) =>
                              setReimbursementRate(Number(e.target.value))
                            }
                            className="pl-7"
                          />
                        </div>
                        <p className="text-sm text-[#737373]">
                          Based on typical RPM/RTM billing codes
                          ($120&ndash;$150)
                        </p>
                      </div>
                    </div>

                    {/* Platform Fee */}
                    <div>
                      <Label
                        htmlFor="platform-fee"
                        className="text-base font-semibold mb-3 block"
                      >
                        iRxReminder Fee per Patient/Month
                      </Label>
                      <div className="flex items-center gap-4">
                        <div className="relative flex-1 max-w-xs">
                          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-[#737373]">
                            $
                          </span>
                          <Input
                            id="platform-fee"
                            type="number"
                            value={platformFee}
                            onChange={(e) =>
                              setPlatformFee(Number(e.target.value))
                            }
                            className="pl-7"
                          />
                        </div>
                        <p className="text-sm text-[#737373]">
                          Platform + device cost
                        </p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Right: Live Results */}
                <div className="flex flex-col">
                  {/* Hero stat — Net Profit */}
                  <div className="relative rounded-2xl p-8 overflow-hidden mb-6 bg-[#171717]">
                    <div className="relative">
                      <p className="text-xs font-semibold uppercase tracking-[0.05em] text-[#B3CCFF] mb-2">
                        Projected Net Profit
                      </p>
                      <p
                        className="text-4xl md:text-5xl font-bold text-white tracking-tight mb-1"
                        style={{ fontFamily: "var(--font-display)" }}
                      >
                        {formatCurrency(netProfit)}
                      </p>
                      <p className="text-sm text-[#A3A3A3]">
                        over {duration} month{duration > 1 ? "s" : ""} &middot; {patientCount.toLocaleString()} patients
                      </p>
                    </div>
                  </div>

                  {/* Breakdown rows */}
                  <div className="space-y-3">
                    {[
                      { label: "Reimbursable Revenue", value: formatCurrency(totalRevenue), color: "#1E56A0", bgClass: "bg-[#EEF4FF] border-[#D9E5FF]" },
                      { label: "Program Cost", value: formatCurrency(totalCost), color: "#737373", bgClass: "bg-[#FAFAFA] border-[#E5E5E5]" },
                    ].map((item) => (
                      <div
                        key={item.label}
                        className={`flex items-center justify-between px-5 py-3.5 rounded-xl border ${item.bgClass}`}
                      >
                        <span className="text-sm font-medium text-[#404040]">{item.label}</span>
                        <span
                          className="text-xl font-bold tracking-tight"
                          style={{ color: item.color, fontFamily: "var(--font-display)" }}
                        >
                          {item.value}
                        </span>
                      </div>
                    ))}

                    {/* ROI + Payback row */}
                    <div className="grid grid-cols-2 gap-3">
                      <div className="flex flex-col items-center justify-center px-4 py-4 rounded-xl bg-[#EEF4FF] border border-[#D9E5FF]">
                        <span
                          className="text-2xl font-bold tracking-tight text-[#1E56A0]"
                          style={{ fontFamily: "var(--font-display)" }}
                        >
                          {roiMultiplier}&times;
                        </span>
                        <span className="text-xs font-medium text-[#737373] mt-1">ROI Multiplier</span>
                      </div>
                      <div className="flex flex-col items-center justify-center px-4 py-4 rounded-xl bg-[#D1FAE5]/30 border border-[#10B981]/20">
                        <span
                          className="text-2xl font-bold tracking-tight text-[#059669]"
                          style={{ fontFamily: "var(--font-display)" }}
                        >
                          {paybackMonths > 0 ? `~${paybackMonths} mo` : "Instant"}
                        </span>
                        <span className="text-xs font-medium text-[#737373] mt-1">Payback Period</span>
                      </div>
                    </div>
                  </div>

                  {/* Trust badges */}
                  <div className="mt-6">
                    <FloatingBadgeGroup
                      badges={[
                        { icon: Shield, text: "NIH-Funded" },
                        { icon: TrendingUp, text: "80%+ Adherence" },
                        { icon: DollarSign, text: "RPM/RTM Billable" },
                      ]}
                    />
                  </div>

                  {/* Action buttons */}
                  <div className="mt-4 flex gap-3">
                    <Button
                      onClick={generateReportEmail}
                      variant="outline"
                      className="flex-1 border-[#E5E5E5] hover:border-[#1E56A0] hover:bg-[#EEF4FF] text-[#404040] hover:text-[#1E56A0] transition-colors"
                    >
                      <Mail className="w-4 h-4 mr-2" />
                      Email This Report
                    </Button>
                    <Button
                      asChild
                      className="flex-1 bg-[#1E56A0] hover:bg-[#163D7A] text-white transition-colors hover:shadow-md hover:shadow-[#1E56A0]/20"
                    >
                      <Link to="/schedule-pilot">
                        Schedule a Pilot
                        <ArrowRight className="w-4 h-4 ml-2" />
                      </Link>
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </FadeUp>
        </div>
      </section>

      {/* Why Choose */}
      <section className="py-24 bg-[#FAFAFA]">
        <div className="max-w-5xl mx-auto px-5 sm:px-8">
          <FadeUp>
            <h2
              className="text-3xl font-bold text-[#171717] mb-10 text-center tracking-[-0.01em]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Why Health Systems Choose iRxReminder
            </h2>
          </FadeUp>

          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: CheckCircle2,
                title: "Proven Clinical Outcomes",
                desc: "NIH-funded studies demonstrate 48% to 80%+ improvement in medication adherence, reducing readmissions and improving patient safety.",
                color: "#0F2B57",
              },
              {
                icon: Settings,
                title: "Seamless Workflow",
                desc: "100% EHR integration means care teams get real-time adherence data without changing workflows. Pharmacy-loaded pods eliminate setup complexity.",
                color: "#1E56A0",
              },
              {
                icon: DollarSign,
                title: "Fully Reimbursable",
                desc: "The platform qualifies for RPM and RTM billing codes, generating revenue that covers program costs and delivers positive ROI.",
                color: "#059669",
              },
            ].map((item, i) => (
              <FadeUp key={item.title} delay={i * 0.08}>
                <div className="bg-white p-7 rounded-2xl border border-[#E5E5E5]/60 h-full hover:shadow-lg hover:shadow-[#1E56A0]/5 transition-[box-shadow,transform] duration-300 hover:-translate-y-0.5">
                  <div
                    className="w-11 h-11 rounded-xl flex items-center justify-center mb-5"
                    style={{ backgroundColor: `${item.color}1a` }}
                  >
                    <item.icon
                      className="w-5 h-5"
                      style={{ color: item.color }}
                    />
                  </div>
                  <h3 className="font-bold text-[#171717] mb-2">
                    {item.title}
                  </h3>
                  <p className="text-sm text-[#737373] leading-relaxed">
                    {item.desc}
                  </p>
                </div>
              </FadeUp>
            ))}
          </div>

          <FadeUp delay={0.2}>
            <div className="text-center mt-10">
              <Button
                asChild
                variant="outline"
                size="lg"
                className="border-[#1E56A0]/20 text-[#1E56A0] hover:bg-[#1E56A0] hover:text-white transition-colors"
              >
                <Link to="/evidence">View Clinical Validation</Link>
              </Button>
            </div>
          </FadeUp>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-[#1E56A0] py-16">
        <div className="max-w-4xl mx-auto px-5 sm:px-8 text-center">
          <FadeUp>
            <h2
              className="text-3xl md:text-4xl font-bold text-white mb-4 tracking-[-0.01em]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              Ready to Start Your Pilot Program?
            </h2>
            <p className="text-xl text-white/80 mb-8">
              Let&rsquo;s discuss how iRxReminder can deliver measurable
              outcomes for your health system
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                asChild
                size="lg"
                className="bg-white text-[#1E56A0] hover:bg-[#F5F5F5] transition-colors"
              >
                <Link to="/schedule-pilot">
                  Schedule a Pilot
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Link>
              </Button>
            </div>
          </FadeUp>
        </div>
      </section>
    </div>
  );
}
